apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: singhgautam-com-tls
spec:
  secretName: singhgautam-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: singhgautam.com
  dnsNames:
    - singhgautam.com
    - www.singhgautam.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - singhgautam.com
          - www.singhgautam.com